[phases.setup]
nixPkgs = ["nodejs", "wget"]
aptPkgs = ["curl"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node server.js"
onFailure = "restart"

[start.healthcheck]
interval = "30s"
timeout = "300s"
retries = 5
